### ISSUE TITLE
NullPointerException at V4ListenerFragment.onStart

### ISSUE THREAD

**Issue by githubtongdu** [huburt-Hu/NewbieGuide#10]
版本：1.1.1
调用：在主界面的底部按钮点击事件中
```
    @OnClick({R.id.ll_tab_task, R.id.ll_tab_master, R.id.ll_tab_me})
    public void onTabClick(final View view) {
        if (view.getId() == R.id.ll_tab_task) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    SystemClock.sleep(768);
                    if (isFinishing()) return;
                    llTabTask.post(new Runnable() {
                        @Override
                        public void run() {
                            Controller controller = NewbieGuide.with(MainTabActivity.this)//传入activity
                                    .setOnGuideChangedListener(new OnGuideChangedListener() {
                                        @Override
                                        public void onShowed(final Controller controller) {
                                            // 获取布局，然后查找其中的文本按钮，并设置点击事件
                                            GuideLayout layout = ViewUtils.getGuideLayout(controller);
                                            if (layout == null || layout.findViewById(R.id.tv_known) == null) return;
                                            TextView tvKnown = layout.findViewById(R.id.tv_known);
                                            tvKnown.setOnClickListener(new View.OnClickListener() {
                                                @Override
                                                public void onClick(View view) {
                                                    controller.remove();
                                                }
                                            });
                                        }

                                        @Override
                                        public void onRemoved(Controller controller) {
                                            onTabClick(tabs.get(1));
                                        }
                                    })
                                    .setLabel(Consts.Config.GUIDE_LABEL_SHARE2EARN)//设置引导层标示，用于区分不同引导层，必传！否则报错
                                    .addHighLight(llTabTask, HighLight.Type.CIRCLE)//添加需要高亮的view
                                    .setLayoutRes(R.layout.guide_newbie_task)//自定义的提示layout，不要添加背景色，引导层背景色通过setBackgroundColor()设置
                                    .setEveryWhereCancelable(Consts.Config.GUIDE_NEWBIE_CLICK_ANYWHERE)
                                    .alwaysShow(Consts.Config.GUIDE_NEWBIE_SHOW_ALWAYS)
                                    .build();
                            controller.show();//显示引导层
                        }
                    });

                }
            }).start();
        }
    }
```
日志信息：
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.toudeng.ddzh/com.toudeng.ddzh.activity.MainTabActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
	at android.app.ActivityThread.access$800(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:229)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
	at com.app.hubert.library.V4ListenerFragment.onStart(V4ListenerFragment.java)
	at android.support.v4.app.Fragment.performStart(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java)
	at android.support.v4.app.Fragment.performStart(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1174)
	at android.app.Activity.performStart(Activity.java:5473)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
	at android.app.ActivityThread.access$800(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:229)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by huburt-Hu** [comment]
不好意思，前段时间因为个人的事情，没能及时回复你。
关于这个问题你调用的代码不会引起该NullPonitException，是否还有别的地方有调用？

**Comment by huburt-Hu** [comment]
NewbieGuide.with(MainTabActivity.this)这边传入的activity，所以根本不会触发com.app.hubert.library.V4ListenerFragment这个类的代码

**Comment by githubtongdu** [comment]
多谢回复。

新手引导 控件只在MainTabActivity及其下的2个fragment中有调用。
这个错误是友盟统计中记录的，暂时只出现过一次，没法重现，所以临时处理是异常捕获了MainTabActivity中的代码。

**Comment by huburt-Hu** [comment]
Activity中调用肯定是没有问题的，能否把fragment中的调用给我看下

**Comment by huburt-Hu** [comment]
我顺便提一下，如果你需要自定义的引导布局中点击某个控件就让引导层消失，直接在setLayoutRes方法的第二个参数传入控件id就可以，例如你的代码可以这样修改：
```
 @OnClick({R.id.ll_tab_task, R.id.ll_tab_master, R.id.ll_tab_me})
    public void onTabClick(final View view) {
        if (view.getId() == R.id.ll_tab_task) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    SystemClock.sleep(768);
                    if (isFinishing()) return;
                    llTabTask.post(new Runnable() {
                        @Override
                        public void run() {
                            NewbieGuide.with(MainTabActivity.this)
                                    .setOnGuideChangedListener(new OnGuideChangedListener() {
                                        @Override
                                        public void onShowed(final Controller controller) {
                                        }

                                        @Override
                                        public void onRemoved(Controller controller) {
                                            onTabClick(tabs.get(1));
                                        }
                                    })
                                    .setLabel(Consts.Config.GUIDE_LABEL_SHARE2EARN)
                                    .addHighLight(llTabTask, HighLight.Type.CIRCLE)
                                    .setLayoutRes(R.layout.guide_newbie_task, R.id.tv_known)//此处直接传入id即可
                                    .setEveryWhereCancelable(Consts.Config.GUIDE_NEWBIE_CLICK_ANYWHERE)
                                    .alwaysShow(Consts.Config.GUIDE_NEWBIE_SHOW_ALWAYS)
                                    .show();
                        }
                    });
                }
            }).start();
        }
    }
```

**Comment by githubtongdu** [comment]
`.setLayoutRes(R.layout.guide_newbie_task, R.id.tv_known)//此处直接传入id即可`
就知道有更方便的方法，结果我还反射去拿view。有空还是要多看看源码学习下。

那再麻烦你帮忙看看，另外3处的调用
1.TeacherFragment中，在其显示时调用
```
 @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);

        if (isVisibleToUser) {
            final View view = getView();

            new Thread(new Runnable() {
                @Override
                public void run() {
                    SystemClock.sleep(512);
                    view.post(new Runnable() {
                        @Override
                        public void run() {
                            Controller controller = NewbieGuide.with(TeacherFragment.this)//传入activity
                                    .setOnGuideChangedListener(new OnGuideChangedListener() {
                                        @Override
                                        public void onShowed(final Controller controller) { }

                                        @Override
                                        public void onRemoved(Controller controller) {
                                            ((MainTabActivity) getActivity()).onTabClick(
                                                    ((MainTabActivity) getActivity()).tabs.get(((MainTabActivity) getActivity()).tabs.size()-1));
                                        }
                                    })
                                    .setLabel(Consts.Config.GUIDE_LABEL_SUBS)//设置引导层标示，用于区分不同引导层，必传！否则报错
                                    .addHighLight(llGetSubs, HighLight.Type.RECTANGLE)//添加需要高亮的view
                                    .setLayoutRes(R.layout.guide_newbie_get_subs, R.id.tv_known)//自定义的提示layout，不要添加背景色，引导层背景色通过setBackgroundColor()设置
                                    .setEveryWhereCancelable(Consts.Config.GUIDE_NEWBIE_CLICK_ANYWHERE)
                                    .alwaysShow(Consts.Config.GUIDE_NEWBIE_SHOW_ALWAYS)
                                    .build();
                            controller.show();//显示引导层
                        }
                    });

                }
            }).start();
        }
    }
```

2.MineFragment中第一处，在其显示时调用

```
    @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);

        if (isVisibleToUser) {
            if (!hasShowAd) {
                adTimer();
            }

            final View view = getView();
//            final LinearLayout ll = view.findViewById(R.id.ll_withdraw);
            boolean hasShowWithdraw = SharePrefUtils.getBoolValue(Consts.SharePref.File.NEWBIE_GUIDE, Consts.Config.GUIDE_LABEL_WITHDRAW, false);
            boolean hasShowService = SharePrefUtils.getBoolValue(Consts.SharePref.File.NEWBIE_GUIDE, Consts.Config.GUIDE_LABEL_SERVICE, false);
            if (!hasShowWithdraw || !hasShowService) {
                msvContent.fullScroll(ScrollView.FOCUS_DOWN);
            }

            if (hasShowWithdraw && !hasShowService) {
                mHandler.sendEmptyMessage(MSG_TYPE_GUIDE_SERVICE);
                return;
            }

            new Thread(new Runnable() {
                @Override
                public void run() {
                    SystemClock.sleep(512);
                    view.post(new Runnable() {
                        @Override
                        public void run() {
                            Controller controller = NewbieGuide.with(MineFragment.this)//传入activity
                                    .setOnGuideChangedListener(new OnGuideChangedListener() {
                                        @Override
                                        public void onShowed(final Controller controller) { }

                                        @Override
                                        public void onRemoved(Controller controller) {
                                            mHandler.sendEmptyMessage(MSG_TYPE_GUIDE_SERVICE);
                                        }
                                    })
                                    .setLabel(Consts.Config.GUIDE_LABEL_WITHDRAW)//设置引导层标示，用于区分不同引导层，必传！否则报错
                                    .addHighLight(llWithdraw, HighLight.Type.RECTANGLE)//添加需要高亮的view
                                    .setLayoutRes(R.layout.guide_newbie_share2earn, R.id.tv_known)//自定义的提示layout，不要添加背景色，引导层背景色通过setBackgroundColor()设置
                                    .setEveryWhereCancelable(Consts.Config.GUIDE_NEWBIE_CLICK_ANYWHERE)
                                    .alwaysShow(Consts.Config.GUIDE_NEWBIE_SHOW_ALWAYS)
                                    .build();
                            controller.show();//显示引导层
                        }
                    });

                }
            }).start();
        }
    }
```
第二处，mHandler中的处理片段
```
case MSG_TYPE_GUIDE_SERVICE:
                    msvContent.post(new Runnable() {
                    @Override
                    public void run() {
                            SystemClock.sleep(512);
                            Controller controller = NewbieGuide.with(MineFragment.this)//传入activity
                                .setOnGuideChangedListener(new OnGuideChangedListener() {
                                    @Override
                                    public void onShowed(final Controller controller) { }

                                    @Override
                                    public void onRemoved(Controller controller) { }
                                })
                                .setLabel(Consts.Config.GUIDE_LABEL_SERVICE)//设置引导层标示，用于区分不同引导层，必传！否则报错
                                .addHighLight(llService, HighLight.Type.RECTANGLE)//添加需要高亮的view
                                .setLayoutRes(R.layout.guide_newbie_contact_service, R.id.tv_known)//自定义的提示layout，不要添加背景色，引导层背景色通过setBackgroundColor()设置
                                .setEveryWhereCancelable(Consts.Config.GUIDE_NEWBIE_CLICK_ANYWHERE)
                                .alwaysShow(Consts.Config.GUIDE_NEWBIE_SHOW_ALWAYS)
                                .build();
                        controller.show();//显示引导层
                    }
                    });
                    break;
```

**Comment by huburt-Hu** [comment]
推测空指针可能是fragment快速切换时出现的，建议这里的`SystemClock.sleep(512);`去除，post方法本身就是延迟到view加载完成时执行，没必要在延迟512毫秒了。有可能在延迟的这段时间内切换fragment会出现问题。

**Comment by githubtongdu** [comment]
刚刚测了下，分别在模拟器(5.1.1)和真机(4.4.2)上，将延迟增加了10倍；
然后在引导界面未出来前，多次切换fragment；
发现并未导致应用崩溃或者日志报错，只是出现了多个引导界面重叠的状况；可惜没有拿到报错机型。
可能不是fragment切换导致空指针的，因为：
1.主界面fragment不多只有3个，都通过ViewPager.setOffscreenPageLimit(3)缓存起来了；
2.引导界面设置了setEveryWhereCancelable(false)，所以显示引导后用户无法切换

**Comment by githubtongdu** [comment]
刚刚又报了一条错，出错的地方在上面提到的 MineFragment中第一处

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
	at com.app.hubert.library.Controller.<init>(Controller.java)
	at com.app.hubert.library.Builder.build(Builder.java)
	at com.toudeng.ddzh.fragment.MineFragment$5$1.run(MineFragment.java)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5911)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

**Comment by githubtongdu** [comment]
似乎是this.activity为null，
 ```
   public Builder(android.support.v4.app.Fragment v4Fragment) {
        this.v4Fragment = v4Fragment;
        this.activity = v4Fragment.getActivity();
    }
```

```
    public Controller(Builder builder) {
        this.activity = builder.getActivity();
        this.fragment = builder.getFragment();
        this.v4Fragment = builder.getV4Fragment();
        this.list = builder.getList();
        this.backgroundColor = builder.getBackgroundColor();
        this.onGuideChangedListener = builder.getOnGuideChangedListener();
        this.everyWhereCancelable = builder.isEveryWhereCancelable();
        this.label = builder.getLabel();
        this.alwaysShow = builder.isAlwaysShow();
        this.layoutResId = builder.getLayoutResId();
        this.viewIds = builder.getViewIds();
        this.fullScreen = builder.isFullScreen();
        this.mParentView = (FrameLayout)this.activity.getWindow().getDecorView();
        this.sp = this.activity.getSharedPreferences("NewbieGuide", 0);
    }
```

难道activity.isFinishing()？

**Comment by huburt-Hu** [comment]
在fragment使用的话会通过getActivity方法获取到依附的Activity，这个crash说明，执行显示引导层显示代码的时候fragment已经从activity移除了，所以getActivity方法获取的时null

**Comment by huburt-Hu** [comment]
这个真的应该是延时的引出的

**Comment by githubtongdu** [comment]
多谢回复，不过这个场景在开发测试环境一直无法重现。

现在在调用NewbieGuide控件前，加了如下判断：
`
            if (!(getActivity() != null && !getActivity().isFinishing() && isAdded())) return;`

p.s.同时谢谢1.2的更新，多页引导使用更方便

**Comment by huburt-Hu** [comment]
不客气，以后遇到啥问题随时提出~ 我看到会第一时间回复
