### ISSUE TITLE
多个引导崩溃，崩溃信息如下

### ISSUE THREAD

**Issue by NicodeLee** [huburt-Hu/NewbieGuide#194]
`    java.lang.OutOfMemoryError: Failed to allocate a 74649612 byte allocation with 16777216 free bytes and 47MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:720)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
        at android.content.res.Resources.loadDrawable(Resources.java:858)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.view.View.<init>(View.java:4202)
        at android.view.ViewGroup.<init>(ViewGroup.java:581)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:248)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:244)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:240)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.app.hubert.guide.core.GuideLayout.addCustomToLayout(GuideLayout.java:199)
        at com.app.hubert.guide.core.GuideLayout.onAttachedToWindow(GuideLayout.java:185)
        at android.view.View.dispatchAttachedToWindow(View.java:15509)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2943)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4483)
        at android.view.ViewGroup.addView(ViewGroup.java:4285)
        at android.view.ViewGroup.addView(ViewGroup.java:4257)
        at com.app.hubert.guide.core.Controller.showGuidePage(Controller.java:175)
        at com.app.hubert.guide.core.Controller.showNextOrRemove(Controller.java:187)
        at com.app.hubert.guide.core.Controller.access$700(Controller.java:39)
        at com.app.hubert.guide.core.Controller$3.onGuideLayoutDismiss(Controller.java:172)
        at com.app.hubert.guide.core.GuideLayout.dismiss(GuideLayout.java:255)
        at com.app.hubert.guide.core.GuideLayout.remove(GuideLayout.java:247)
        at com.app.hubert.guide.core.GuideLayout$1.onClick(GuideLayout.java:89)
        at android.view.View.performClick(View.java:5637)
        at com.app.hubert.guide.core.GuideLayout.performClick(GuideLayout.java:97)
        at com.app.hubert.guide.core.GuideLayout.onTouchEvent(GuideLayout.java:123)
        at android.view.View.dispatchTouchEvent(View.java:10023)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2653)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2348)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2348)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2348)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2348)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2348)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
2021-07-13 16:11:33.834 4087-4087/com.qi.trafficproxy E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3080)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
        at android.view.View.dispatchPointerEvent(View.java:10243)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6145)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2021-07-13 16:11:38.350 4087-4170/com.qi.trafficproxy I/crashsdk: crashsdk uploading logs
`

**Comment by AaronOhO** [comment]
看堆栈可能是你引用的drawable资源太大了吧   tinypng压缩一下看看
