### ISSUE TITLE
Oppo R9s 在设置heightView 为adapter中的一个View 异常退出错误log如下

### ISSUE THREAD

**Issue by xiaojintongxue** [huburt-Hu/NewbieGuide#52]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getHitRect(android.graphics.Rect)' on a null object reference
at com.app.hubert.guide.util.ViewUtils.getLocationInView(ViewUtils.java:36)
at com.app.hubert.guide.model.HighLight.getRectF(HighLight.java:72)
at com.app.hubert.guide.core.GuideLayout.drawHightLights(GuideLayout.java:82)
at com.app.hubert.guide.core.GuideLayout.onDraw(GuideLayout.java:75)
at android.view.View.draw(View.java:16221)
at android.view.View.buildDrawingCacheImpl(View.java:15518)
at android.view.View.buildDrawingCache(View.java:15379)
at android.view.View.updateDisplayListIfDirty(View.java:15199)
at android.view.View.draw(View.java:15991)
at android.view.ViewGroup.drawChild(ViewGroup.java:3648)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3438)
at android.view.View.draw(View.java:16224)
at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2739)
at android.view.View.updateDisplayListIfDirty(View.java:15218)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2773)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2592)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1209)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6330)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
at android.view.Choreographer.doCallbacks(Choreographer.java:674)
at android.view.Choreographer.doFrame(Choreographer.java:610)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:179)
at android.app.ActivityThread.main(ActivityThread.java:5769)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by huburt-Hu** [comment]
出现这种情况的原因是高亮的view没有在屏幕上显示了

**Comment by 1206010214** [comment]
同样遇到类似的问题，那也不应该抛异常吧？看了源码里面com.app.hubert.guide.util.ViewUtils.getLocationInView(View parent, View child){}
`public static Rect getLocationInView(View parent, View child) {
        if(child != null && parent != null) { //此处判读了非空情况
            View decorView = null;
            Context context = child.getContext();
            if(context instanceof Activity) {
                decorView = ((Activity)context).getWindow().getDecorView();
            }

            Rect result = new Rect();
            Rect tmpRect = new Rect();
            View tmp = child;
            if(child == parent) {
                child.getHitRect(result);
                return result;
            } else {
                while(tmp != decorView && tmp != parent) {//此处也应该判断非空的情况，捕获该异常，结束后续操作，因为在while循环的时候，此处可能为空了
                    tmp.getHitRect(tmpRect);
                    if(!tmp.getClass().equals("NoSaveStateFrameLayout")) {
                        result.left += tmpRect.left;
                        result.top += tmpRect.top;
                    }

                    tmp = (View)tmp.getParent();
                    if(tmp != null && tmp.getParent() != null && tmp.getParent() instanceof ViewPager) {
                        tmp = (View)tmp.getParent();
                    }
                }

                result.right = result.left + child.getMeasuredWidth();
                result.bottom = result.top + child.getMeasuredHeight();
                return result;
            }
        } else {
            throw new IllegalArgumentException("parent and child can not be null .");
        }
    }`
