### ISSUE TITLE
设置相对布局，高亮view有偏移，怎么回事，麻烦帮忙看下？

### ISSUE THREAD

**Issue by TopTime1** [huburt-Hu/NewbieGuide#63]
public void showRelativeGuide() {
        HighlightOptions options = new HighlightOptions.Builder()
                .setRelativeGuide(new RelativeGuide(R.layout.info_known, Gravity.TOP) {
                    @Override
                    protected void onLayoutInflated(View view) {
//                        TextView textView = view.findViewById(R.id.tv);
//                        textView.setText("inflated");
                    }
                })
                .setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
//                        Toast.makeText(FirstActivity.this, "highlight click", Toast.LENGTH_SHORT).show();
                    }
                })
                .build();
        RelativeGuide relativeGuide =new RelativeGuide(R.layout.info_known, Gravity.TOP);
//        GuidePage page = GuidePage.newInstance()
//                .addHighLightWithOptions(frag5_yue, options);
        GuidePage page =  GuidePage.newInstance()//创建一个实例
                .addHighLight(frag5_yue,relativeGuide);//添加高亮的view
//                .setLayoutRes(R.layout.info_known);//设置引导页布局

        NewbieGuide.with(this)
                .setLabel("relative")
                .alwaysShow(true)//总是显示，调试时可以打开
                .addGuidePage(page)
                .show();
    }
![image](https://user-images.githubusercontent.com/7701170/44185360-66d7c700-a146-11e8-8e4b-f1502b5eeca0.png)

**Comment by huburt-Hu** [comment]
设置anchor为界面xml的根布局

**Comment by huburt-Hu** [comment]
手机是什么牌子的？努比亚？

**Comment by TopTime1** [comment]
诺基亚vivo都不行，设置相对布局就会有这个，不设置正常

**Comment by TopTime1** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.indexOfChild(android.view.View)' on a null object reference
        at com.app.hubert.guide.core.Controller.<init>(Controller.java:78)
        at com.app.hubert.guide.core.Builder.show(Builder.java:122)
        at cn.com.zwwl.bayuwen.fragment.MainFrag5.showRelativeGuide(MainFrag5.java:481)
        at cn.com.zwwl.bayuwen.fragment.MainFrag5.initView(MainFrag5.java:184)
        at cn.com.zwwl.bayuwen.fragment.MainFrag5.onCreateView(MainFrag5.java:100)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6771)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by TopTime1** [comment]
设置anchor为界面xml的根布局,设置了直接报错

**Comment by TopTime1** [comment]
设置了anchor也不行，是不是超出屏幕了，算位置算的有问题啊？因为有用ScrollView

**Comment by huburt-Hu** [comment]
你anchor传了什么？这个ViewGroup没有父布局，并且也不是FrameLayout，是不是还没有添加到屏幕上

**Comment by TopTime1** [comment]
不是，<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/frag5_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/body_bg">


    <ScrollView
        android:id="@+id/frag5_sv"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:id="@+id/frag5_li_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">
这是我外层的布局，我传frag5_li_layout，可以显示，但是还是偏移

**Comment by TopTime1** [comment]
还有个问题我设置相对布局后，水平居中不好使了

**Comment by huburt-Hu** [comment]
```
GuidePage page = GuidePage.newInstance()
.addHighLight(frag5_yue);
    NewbieGuide.with(this)
            .setLabel("relative")
            .alwaysShow(true)
            .addGuidePage(page)
            .show();
```
你确定这样使用高亮不会偏移？
只是加上`.addHighLight(frag5_yue,relativeGuide);`这个就偏移了？

**Comment by huburt-Hu** [comment]
相对布局就即没有水平居中的设置啊

**Comment by TopTime1** [comment]
是的啊，测试过了，相对布局设置水平居中了<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">


    <ImageView
        android:id="@+id/ik_arrow_iv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:src="@drawable/campus_arrow_icon" />

    <TextView
        android:id="@+id/ik_prompt_tv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/ik_arrow_iv"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="5dp"
        android:text="这里可以选择上课地点"
        android:textColor="@color/white"
        android:textSize="@dimen/text_size_15" />

    <TextView
        android:id="@+id/ik_btn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/ik_prompt_tv"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="10dp"
        android:background="@drawable/got_it_bg"
        android:paddingBottom="6dp"
        android:paddingLeft="12dp"
        android:paddingRight="12dp"
        android:paddingTop="6dp"
        android:text="我知道啦"
        android:textColor="@color/f08302"
        android:textSize="@dimen/text_size_14" />


</RelativeLayout>

**Comment by TopTime1** [comment]
查出问题了吗？大佬

**Comment by huburt-Hu** [comment]
我复现不了你的情况

**Comment by TopTime1** [comment]
我放到handler里就好了

**Comment by Nstd** [comment]
https://github.com/huburt-Hu/NewbieGuide/blob/f111513a0d0885686d7988ce418f344acf66741d/guide/src/main/java/com/app/hubert/guide/util/ViewUtils.java#L15-L54

因为这个方法在计算显示位置的时候，没有考虑到scrollview的滑动

最好是库能判断是否超出屏幕，超出屏幕的时候，看能不能通过滑动来显示出该view，然后再计算显示位置

**Comment by hnty545** [comment]
@TopTime1 放在handler里能解决吗，请问代码是怎样的
