### ISSUE TITLE
反馈报错日志（极少出现）

### ISSUE THREAD

**Issue by zijincliff** [huburt-Hu/NewbieGuide#91]
报错日志如下：
java.lang.NullPointerException: Attempt to invoke interface method 'void com.app.hubert.guide.lifecycle.a.b()' on a null object reference
    at com.app.hubert.guide.lifecycle.V4ListenerFragment.onStart(V4ListenerFragment.java:25)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2378)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
    at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)

**Comment by zhangshaobo87** [comment]
作者大大修复了这个问题了吗，我这也报这个问题

**Comment by zijincliff** [comment]
> 作者大大修复了这个问题了吗，我这也报这个问题

目前来看应该是fragment获取的activity为null，可以试着延迟已经判断非空来处理一下先

**Comment by zhangshaobo87** [comment]
好的，会在最新的版本修复这个问题吗

**Comment by zijincliff** [comment]
那样的话就不在fragment里面使用，在fragment所属的activity里使用，通过回调来触发回到activity后使用

**Comment by huburt-Hu** [comment]
其实是监听fragment的空指针，问题已经修复，之后会发布一个新版本
